<a href="https://colab.research.google.com/github/davidivan13/Python-for-Data-Science/blob/main/NumPy_101_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install numpy

In [2]:
import numpy as np

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

- object : Objek apa pun yang mengekspos metode antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
- dtype  : type data, opsional
- copy   : Opsional. Secara default (True), objek disalin
- order  : C (baris mayor) atau F (utama kolom) atau A (apa saja) (default)
- subok  : Secara default, array yang dikembalikan dipaksa menjadi array kelas dasar. Jika benar, sub-kelas akan diberikan
- ndimin : Menentukan dimensi minimum dari array yang dihasilkan

In [3]:
# Contoh 1
# Masukkan nilai integer atau nilai dengan tipe data apapun sesuai kebutuhan
arr = np.array([1,2,3])

In [4]:
print(arr)

[1 2 3]


In [5]:
arr[2]

np.int64(3)

In [6]:
# Contoh 2 array 2 dimensi
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


Tipe Data Array

In [7]:
# contoh 1 array dengan tipe data integer
print(a.dtype)

int64


In [8]:
# contoh 2 tipe data dengan unicode string
arr_1 = np.array(['rambutan', 'apel', 'jeruk'])
print(arr_1.dtype)
arr_1 = np.array(['r', 'a', 'j'])
print(arr_1.dtype)

<U8
<U1


In [9]:
#contoh 3 tipe data yang didefinisikan
arr_2 = np.array([1, 2, 3, 4], dtype='S')

print(arr_2)
print(arr_2.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [10]:
#contoh 4 tipe data yang diubah
arrs = np.array([1.1, 2.1, 3.1])

newarr = arrs.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Membuat array dari existed data (yang sudah ada)

In [11]:
#konversi list menjadi ndarray

x = [1, 2, 3, 4, 5]
print(type(x))
x = np.asarray(x)
print(x.dtype)
print(x)

<class 'list'>
int64
[1 2 3 4 5]


In [12]:
# contoh kedua konversi list menjadi array dengan tipe data yang didefinisikan
x = [1, 2, 3, 4, 5]
print(type(x))
x = np.asarray(x, dtype='f')
print(x.dtype)
print(x)

<class 'list'>
float32
[1. 2. 3. 4. 5.]


# Task 1 untuk audience :
- Buat dua variable tuple yang berisi angka
- masukkan dua variable tuple tersebut kedalam variable bertipe data list
- konversi list tersebut menjadi array numpy

In [13]:
# Isi disini
arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])
kumpulandata = [arr1, arr2]
datalist = np.asarray(kumpulandata)
print(datalist)

[[1 3 5]
 [2 4 6]]


Membuat rentang nilai menggunakan numpy (STUDY CASE) :
membuat dataframe menggunakan rentang nilai random dan deterministik



numpy.arange(start, stop, step, dtype)

In [14]:
z = np.arange(0, 1, 0.1, dtype='f')
x = np.arange(1,11, 1)
y = np.arange(10,20, 1)

In [15]:
print(z)
print(x)
print(y)

[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]


In [16]:
import pandas as pd

In [17]:
pd.DataFrame({'z' : z, 'x' : x, 'y' : y})

z   x   y
0  0.0   1  10
1  0.1   2  11
2  0.2   3  12
3  0.3   4  13
4  0.4   5  14
5  0.5   6  15
6  0.6   7  16
7  0.7   8  17
8  0.8   9  18
9  0.9  10  19

Operasi umum lain di NumPy beserta tugas untuk audience

In [18]:
#membuat array dengan nilai 1 di numpy
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
#membuat array dengan nilai 0 di numpy
x = np.zeros((5,7))
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [20]:
x = np.full((3,4), 0.72)
print(x)

[[0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]]


In [21]:
x = np.random.rand(5,3)
print(x)

[[0.83701766 0.00948374 0.08662416]
 [0.30209082 0.94048003 0.77546927]
 [0.42159633 0.43494097 0.0515541 ]
 [0.65024894 0.19567312 0.85616584]
 [0.94491626 0.41596439 0.9901544 ]]


In [22]:
pd.DataFrame(x, columns=['x', 'y', 'z'])

x         y         z
0  0.837018  0.009484  0.086624
1  0.302091  0.940480  0.775469
2  0.421596  0.434941  0.051554
3  0.650249  0.195673  0.856166
4  0.944916  0.415964  0.990154

In [23]:
#Tugas 1 :Generate random array menggunakan np.random.rand dengan jumlah baris 3 serta jumlah kolom 4 dan masukkan ke dalam dataframe
x = np.random.rand(3,4)
pd.DataFrame(x, columns=['col 1', 'col 2', 'col 3', 'col 4'])

col 1     col 2     col 3     col 4
0  0.308389  0.301778  0.530648  0.344865
1  0.182383  0.193211  0.308567  0.628494
2  0.180933  0.457556  0.423851  0.719065

In [24]:
#Tugas 2 :Generate array dengan nilai satu dan nol yang memiliki baris 5 dan 6 kolom di dua variable berbeda kemudian konversi ke dataframe dan concat keduanya
arr_ones = np.ones((5,6))
arr_zeros = np.zeros((5,6))
df_ones = pd.DataFrame(arr_ones, columns=['col 1', 'col 2', 'col 3', 'col 4', 'col 5', 'col 6'])
df_zeros = pd.DataFrame(arr_zeros, columns=['col 1', 'col 2', 'col 3', 'col 4', 'col 5', 'col 6'])
df_concat = pd.concat([df_ones, df_zeros], ignore_index=True)
df_concat.head(10)

col 1  col 2  col 3  col 4  col 5  col 6
0    1.0    1.0    1.0    1.0    1.0    1.0
1    1.0    1.0    1.0    1.0    1.0    1.0
2    1.0    1.0    1.0    1.0    1.0    1.0
3    1.0    1.0    1.0    1.0    1.0    1.0
4    1.0    1.0    1.0    1.0    1.0    1.0
5    0.0    0.0    0.0    0.0    0.0    0.0
6    0.0    0.0    0.0    0.0    0.0    0.0
7    0.0    0.0    0.0    0.0    0.0    0.0
8    0.0    0.0    0.0    0.0    0.0    0.0
9    0.0    0.0    0.0    0.0    0.0    0.0